-- ════════════════════════════════════════════════════════════════
-- Migration 027 — Seed Donors from Donor list_M4C.xlsx
--
-- Adds 156 donors (63 CSR, 51 Foundation, 42 HNI)
-- Also adds 'Foundation' and 'HNI' donor_type lookup values
-- Skips any donor whose name already exists in the table
-- ════════════════════════════════════════════════════════════════

-- ── 1. Add new donor_type lookup codes ───────────────────────────
INSERT INTO public.lookup_values (lookup_type, code, label, sort_order)
VALUES
  ('donor_type', 'Foundation', 'Foundation',                35),
  ('donor_type', 'HNI',        'HNI (High Net-Worth)',      45)
ON CONFLICT DO NOTHING;

-- ── 2. Seed 156 donors (skip if name already exists) ─────────────
INSERT INTO public.donor (donor_name, donor_type, is_active)
SELECT v.donor_name, v.donor_type, true
FROM (VALUES
  ('Wells Fargo International Solutions private Limited',    'CSR'),
  ('BPCL',                                                   'CSR'),
  ('United Way of Delhi',                                    'CSR'),
  ('Maheshwari Investors Private Limited',                   'CSR'),
  ('DHL Logistics p.ltd',                                    'CSR'),
  ('Teach to Lead',                                          'CSR'),
  ('Mindtech India Limited',                                 'CSR'),
  ('Zyme Solutions Pvt Ltd',                                 'CSR'),
  ('Decor Paper Mills Ltd',                                  'CSR'),
  ('The Boston Consulting Group (India) Pvt Ltd',            'CSR'),
  ('Quality Austria Center',                                 'CSR'),
  ('Ramakrishna English Medium',                             'CSR'),
  ('GGV Managerial Services Pvt Ltd',                        'CSR'),
  ('DHL Logistics Private Limited',                          'CSR'),
  ('Zerodha Broking Ltd',                                    'CSR'),
  ('Zerodha Commodities Private Limited',                    'CSR'),
  ('Zerodha Securities Pvt. Ltd',                            'CSR'),
  ('Tata advanced materials limited',                        'CSR'),
  ('Zyme Solutions Private Limited',                         'CSR'),
  ('Austin Global Ventures Private Limited',                 'CSR'),
  ('United Way of Bengaluru',                                'CSR'),
  ('Jambore Education Pvt Ltd',                              'CSR'),
  ('ThoughtFocus Information Technologies Pvt Ltd',          'CSR'),
  ('United Way Worldwide',                                   'CSR'),
  ('Otis Elevator Company (India) Limited',                  'CSR'),
  ('Micro Focus Software India Private Limited',             'CSR'),
  ('Suburban Diagnostics (India) Private Limited',           'CSR'),
  ('Netapp India Private Limited',                           'CSR'),
  ('Tata Lockheed Martin Aerostructures Limited',            'CSR'),
  ('McKinsey & Company',                                     'CSR'),
  ('Metro Brands Limited',                                   'CSR'),
  ('MFIFLEX Technologies Private Limited',                   'CSR'),
  ('Otis Elevator Company India Limited',                    'CSR'),
  ('Bengal Finance and Investment Private Ltd',              'CSR'),
  ('Tata Boeing Aerospace Limited',                          'CSR'),
  ('Indraprastha Medical Corporation Limited',               'CSR'),
  ('Info Edge India Limited',                                'CSR'),
  ('Ish international limited',                              'CSR'),
  ('Profectus Capital Private Limited',                      'CSR'),
  ('Tata Sikorsky Aerospace Limited',                        'CSR'),
  ('Nova Integrated Systems Limited',                        'CSR'),
  ('DIQU TECH Private Limited',                              'CSR'),
  ('Autonomy Software Asia Private Limited',                 'CSR'),
  ('Arama Suites',                                           'CSR'),
  ('Hindustan Hydraulics Pvt Ltd',                           'CSR'),
  ('Bosch Global Software Technologies Private Limited',     'CSR'),
  ('HCL Foundation',                                         'CSR'),
  ('Micro Focus Software India Private Limited (Open Text)', 'CSR'),
  ('Oaklane Capital Management LLP',                         'CSR'),
  ('Malladi Drugs and Pharmaceuticals Limited',              'CSR'),
  ('Sasken Technologies Limited',                            'CSR'),
  ('Sokrati Technologies Private Limited',                   'CSR'),
  ('Dentsu Advertising and Media Services India Private Limited', 'CSR'),
  ('Info Edge(India)Limited',                                'CSR'),
  ('Optiva India Technologies Private Limited',              'CSR'),
  ('Vinir Engineering Pvt Ltd',                              'CSR'),
  ('HDFC Bank Limited',                                      'CSR'),
  ('Axis Bank Limited',                                      'CSR'),
  ('Salesforce.Com India Private Limited',                   'CSR'),
  ('L&T Technology Services Limited',                        'CSR'),
  ('Jewelex India Private Limited',                          'CSR'),
  ('Talent500 Tech (India) Private Limited',                 'CSR'),
  ('FrauenPower eV',                                         'CSR'),
  ('Ford Foundation',                                        'Foundation'),
  ('Tech Mahindra Foundation',                               'Foundation'),
  ('Adobe foundation',                                       'Foundation'),
  ('Abako foundation',                                       'Foundation'),
  ('Ekstep Foundation',                                      'Foundation'),
  ('Svantatra charitable trust',                             'Foundation'),
  ('Lets Change Foundation',                                 'Foundation'),
  ('E Governments Foundation',                               'Foundation'),
  ('Lets Do Some Good Foundation',                           'Foundation'),
  ('Nasscom foundation',                                     'Foundation'),
  ('Alphabet club',                                          'Foundation'),
  ('Education above all Foundation',                         'Foundation'),
  ('Sathya Educare Foundation INC',                          'Foundation'),
  ('Lal Pathlabs Foundation',                                'Foundation'),
  ('COMPRO TECHNOLOGIES FOUNDATION',                         'Foundation'),
  ('Abako Foundation',                                       'Foundation'),
  ('Asia Initiative',                                        'Foundation'),
  ('Learning Equality Foundation (Kolibiri)',                 'Foundation'),
  ('ATE Chandra Foundation',                                 'Foundation'),
  ('India Welfare Trust',                                    'Foundation'),
  ('Caring with Colour-A Manasi Kirloskar Initiative',       'Foundation'),
  ('APR Charitable Trust',                                   'Foundation'),
  ('Ashraya Hastha Trust',                                   'Foundation'),
  ('Kasturi Trust',                                          'Foundation'),
  ('THE NUDGE FOUNDATION',                                   'Foundation'),
  ('Asian Venture',                                          'Foundation'),
  ('GDI Solution LLc',                                       'Foundation'),
  ('UK Online Giving foundation',                            'Foundation'),
  ('Education Above All Foundation',                         'Foundation'),
  ('Online Giving Foundation',                               'Foundation'),
  ('Fidelity Asia Pacific Foundation',                       'Foundation'),
  ('Deloitte Foundation',                                    'Foundation'),
  ('Arpan Foundation',                                       'Foundation'),
  ('Dasra',                                                  'Foundation'),
  ('Rotary Club of Queen''s Necklace, Mumbai',               'Foundation'),
  ('Punjab Youth Leaders Initiative Inc',                    'Foundation'),
  ('Public Health Institute',                                'Foundation'),
  ('Max India Foundation',                                   'Foundation'),
  ('Give Foundtion INC',                                     'Foundation'),
  ('Amansa Capital Pte. Ltd',                                'Foundation'),
  ('Mantra4change US',                                       'Foundation'),
  ('Leadership For Skilled Education Foundation',            'Foundation'),
  ('EMpower-The Emerging Markets Foundation',                'Foundation'),
  ('Atlassian Foundation International Limited',             'Foundation'),
  ('Dabhoi Community Foundation',                            'Foundation'),
  ('ANSR Foundation',                                        'Foundation'),
  ('Smt Bhagwanidevi Basudev Jhunjhunwala Trust',            'Foundation'),
  ('Advaith Foundation',                                     'Foundation'),
  ('Dalmia Charitable Trust',                                'Foundation'),
  ('GIVE Foundation Inc',                                    'Foundation'),
  ('R G Manudhane Foundation For Excellence',                'Foundation'),
  ('Deep Kalara',                                            'HNI'),
  ('Mallika Ravi',                                           'HNI'),
  ('Balakrishna',                                            'HNI'),
  ('Rajesh Magow',                                           'HNI'),
  ('Daya Kori',                                              'HNI'),
  ('Suman Kanth Manjal',                                     'HNI'),
  ('R G Manudhane Foundation',                               'HNI'),
  ('Cornelius Walter',                                       'HNI'),
  ('ASHISH RAMESHCHANDRA KACHOLIA',                          'HNI'),
  ('Rohit Sobti',                                            'HNI'),
  ('Akshay Munjal',                                          'HNI'),
  ('Yashaswini Mahesh Samat',                                'HNI'),
  ('Kanchana Shahi',                                         'HNI'),
  ('Debashish Dutta Gupta',                                  'HNI'),
  ('Subodh Kumar',                                           'HNI'),
  ('Sharey Ali Haque',                                       'HNI'),
  ('Suman Srivastava',                                       'HNI'),
  ('Kumari Shibulal JT',                                     'HNI'),
  ('Anil Kumble',                                            'HNI'),
  ('Sanjay Mahesh Purohit',                                  'HNI'),
  ('Kanchana Shahi Gupta',                                   'HNI'),
  ('Bangalore Gangaiah Srinivas',                            'HNI'),
  ('K N Subbaswami',                                         'HNI'),
  ('Chetana Kumble',                                         'HNI'),
  ('ASHUTOSH',                                               'HNI'),
  ('Apurva Arvind Dalal',                                    'HNI'),
  ('Sarojini Damodaran Shibulal',                            'HNI'),
  ('Deepak Madhav Satwalekar',                               'HNI'),
  ('Kodeboyina Hanumantha Rao',                              'HNI'),
  ('Nikunj Pravin Jhaveri',                                  'HNI'),
  ('Jigar Mahesh Kumar Shah',                                'HNI'),
  ('Divanshu Kumar',                                         'HNI'),
  ('Lata Rameshchandra Kacholia',                            'HNI'),
  ('Priyadarshan Mundhra',                                   'HNI'),
  ('ChetanKumar shah',                                       'HNI'),
  ('Dhawal Kiranraj Mehta',                                  'HNI'),
  ('Mr. Sanjay Mahesh Purohit',                              'HNI'),
  ('Mr. Cornelius Walter',                                   'HNI'),
  ('Mr. Priyadarshan Mundhra',                               'HNI'),
  ('Mr. Rameshchandra Gulabchand Kacholia',                  'HNI'),
  ('Mr. Ramesh Mangaleswaran',                               'HNI'),
  ('Mr. Chetan Kumar Shah',                                  'HNI')
) AS v(donor_name, donor_type)
WHERE NOT EXISTS (
  SELECT 1 FROM public.donor d WHERE d.donor_name = v.donor_name
);

-- ── 3. Verify ─────────────────────────────────────────────────────
SELECT donor_type, COUNT(*) AS count
FROM public.donor
WHERE is_active = true
GROUP BY donor_type
ORDER BY donor_type;
